//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZiraatBankPaymentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZiraatBankPaymentService.NkyParaTransferiWSSoap")]
    public interface NkyParaTransferiWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HavaleYap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapResponse> HavaleYapAsync(ZiraatBankPaymentService.HavaleYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EftYap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.EftYapResponse> EftYapAsync(ZiraatBankPaymentService.EftYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurumSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaResponse> DurumSorgulaAsync(ZiraatBankPaymentService.DurumSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurumSorgulaDetay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaDetayResponse> DurumSorgulaDetayAsync(ZiraatBankPaymentService.DurumSorgulaDetayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HavaleYapIsimKontrolIle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapIsimKontrolIleResponse> HavaleYapIsimKontrolIleAsync(ZiraatBankPaymentService.HavaleYapIsimKontrolIleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HavaleYapDovizCevrimli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapDovizCevrimliResponse> HavaleYapDovizCevrimliAsync(ZiraatBankPaymentService.HavaleYapDovizCevrimliRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OkuKur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.KurCevap> OkuKurAsync(string dovizKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IbanSorgula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.IbanSorgulaResponse> IbanSorgulaAsync(ZiraatBankPaymentService.IbanSorgulaRequest request);
    }


    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    //public partial class SecuredWebServiceHeader
    //{

    //    private string kullaniciAdiField;

    //    private string sifreField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    //    public string KullaniciAdi
    //    {
    //        get
    //        {
    //            return this.kullaniciAdiField;
    //        }
    //        set
    //        {
    //            this.kullaniciAdiField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    //    public string Sifre
    //    {
    //        get
    //        {
    //            return this.sifreField;
    //        }
    //        set
    //        {
    //            this.sifreField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class SecuredWebServiceHeader
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string KullaniciAdi = "OVGELEKTRONIK";
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Sifre = "jDNmqFRxZn";
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IbanSorgulamaCevap
    {
        
        private bool ibanGecerliField;
        
        private string ipucuField;
        
        private string cevapMesajiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IbanGecerli
        {
            get
            {
                return this.ibanGecerliField;
            }
            set
            {
                this.ibanGecerliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ipucu
        {
            get
            {
                return this.ipucuField;
            }
            set
            {
                this.ipucuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CevapMesaji
        {
            get
            {
                return this.cevapMesajiField;
            }
            set
            {
                this.cevapMesajiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KurCevap
    {
        
        private decimal alisTutarField;
        
        private int alisPariteBirimField;
        
        private decimal satisTutarField;
        
        private int satisPariteBirimField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal AlisTutar
        {
            get
            {
                return this.alisTutarField;
            }
            set
            {
                this.alisTutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AlisPariteBirim
        {
            get
            {
                return this.alisPariteBirimField;
            }
            set
            {
                this.alisPariteBirimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal SatisTutar
        {
            get
            {
                return this.satisTutarField;
            }
            set
            {
                this.satisTutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SatisPariteBirim
        {
            get
            {
                return this.satisPariteBirimField;
            }
            set
            {
                this.satisPariteBirimField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KurumSorgulaDetayCevap
    {
        
        private string cevapKoduField;
        
        private string cevapMesajiField;
        
        private string muhasabeTarihiField;
        
        private string eftTutarField;
        
        private string muhasabeReferansField;
        
        private string muhasabeSubeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CevapKodu
        {
            get
            {
                return this.cevapKoduField;
            }
            set
            {
                this.cevapKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CevapMesaji
        {
            get
            {
                return this.cevapMesajiField;
            }
            set
            {
                this.cevapMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MuhasabeTarihi
        {
            get
            {
                return this.muhasabeTarihiField;
            }
            set
            {
                this.muhasabeTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EftTutar
        {
            get
            {
                return this.eftTutarField;
            }
            set
            {
                this.eftTutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MuhasabeReferans
        {
            get
            {
                return this.muhasabeReferansField;
            }
            set
            {
                this.muhasabeReferansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MuhasabeSube
        {
            get
            {
                return this.muhasabeSubeField;
            }
            set
            {
                this.muhasabeSubeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DurumSorgulaCevap
    {
        
        private string cevapKoduField;
        
        private string cevapMesajiField;
        
        private string kurumKoduField;
        
        private string kurumAltKoduField;
        
        private string gonderenSubeField;
        
        private string aliciSubeField;
        
        private string bakiyeField;
        
        private string masrafField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CevapKodu
        {
            get
            {
                return this.cevapKoduField;
            }
            set
            {
                this.cevapKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CevapMesaji
        {
            get
            {
                return this.cevapMesajiField;
            }
            set
            {
                this.cevapMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KurumKodu
        {
            get
            {
                return this.kurumKoduField;
            }
            set
            {
                this.kurumKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string KurumAltKodu
        {
            get
            {
                return this.kurumAltKoduField;
            }
            set
            {
                this.kurumAltKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GonderenSube
        {
            get
            {
                return this.gonderenSubeField;
            }
            set
            {
                this.gonderenSubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AliciSube
        {
            get
            {
                return this.aliciSubeField;
            }
            set
            {
                this.aliciSubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Bakiye
        {
            get
            {
                return this.bakiyeField;
            }
            set
            {
                this.bakiyeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Masraf
        {
            get
            {
                return this.masrafField;
            }
            set
            {
                this.masrafField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EftYapCevap
    {
        
        private string cevapKoduField;
        
        private string cevapMesajiField;
        
        private string bankaRefField;
        
        private string muhasebeReferansiField;
        
        private int sorguNoField;
        
        private string transferTipiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CevapKodu
        {
            get
            {
                return this.cevapKoduField;
            }
            set
            {
                this.cevapKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CevapMesaji
        {
            get
            {
                return this.cevapMesajiField;
            }
            set
            {
                this.cevapMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BankaRef
        {
            get
            {
                return this.bankaRefField;
            }
            set
            {
                this.bankaRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MuhasebeReferansi
        {
            get
            {
                return this.muhasebeReferansiField;
            }
            set
            {
                this.muhasebeReferansiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SorguNo
        {
            get
            {
                return this.sorguNoField;
            }
            set
            {
                this.sorguNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TransferTipi
        {
            get
            {
                return this.transferTipiField;
            }
            set
            {
                this.transferTipiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HavaleYapCevap
    {
        
        private string bankaRefField;
        
        private string cevapKoduField;
        
        private string cevapMesajiField;
        
        private string bulunanAliciAcikHesapMusteriNoField;
        
        private string bulunanAliciAcikHesapEkNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BankaRef
        {
            get
            {
                return this.bankaRefField;
            }
            set
            {
                this.bankaRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CevapKodu
        {
            get
            {
                return this.cevapKoduField;
            }
            set
            {
                this.cevapKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CevapMesaji
        {
            get
            {
                return this.cevapMesajiField;
            }
            set
            {
                this.cevapMesajiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BulunanAliciAcikHesapMusteriNo
        {
            get
            {
                return this.bulunanAliciAcikHesapMusteriNoField;
            }
            set
            {
                this.bulunanAliciAcikHesapMusteriNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BulunanAliciAcikHesapEkNo
        {
            get
            {
                return this.bulunanAliciAcikHesapEkNoField;
            }
            set
            {
                this.bulunanAliciAcikHesapEkNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYap", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AliciMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AliciEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string iban;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string DovizCinsi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Tutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string MusteriReferans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string TCKNVKN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string odemeNedeni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string aliciHesapKapaliysaAcikHesabiBul;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string amirAdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string amirHesap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string amirKimlik;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string amirAdres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string amirUlkeSehir;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string amirDogumYeri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string amirDogumTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string amirKurumMusteriNo;
        
        public HavaleYapRequest()
        {
        }
        
        public HavaleYapRequest(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string AliciMusteriNo, 
                    string AliciEkno, 
                    string iban, 
                    string DovizCinsi, 
                    string Tutar, 
                    string Aciklama, 
                    string MusteriReferans, 
                    string TCKNVKN, 
                    string odemeNedeni, 
                    string aliciHesapKapaliysaAcikHesabiBul, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.AliciMusteriNo = AliciMusteriNo;
            this.AliciEkno = AliciEkno;
            this.iban = iban;
            this.DovizCinsi = DovizCinsi;
            this.Tutar = Tutar;
            this.Aciklama = Aciklama;
            this.MusteriReferans = MusteriReferans;
            this.TCKNVKN = TCKNVKN;
            this.odemeNedeni = odemeNedeni;
            this.aliciHesapKapaliysaAcikHesabiBul = aliciHesapKapaliysaAcikHesabiBul;
            this.amirAdi = amirAdi;
            this.amirHesap = amirHesap;
            this.amirKimlik = amirKimlik;
            this.amirAdres = amirAdres;
            this.amirUlkeSehir = amirUlkeSehir;
            this.amirDogumYeri = amirDogumYeri;
            this.amirDogumTarihi = amirDogumTarihi;
            this.amirKurumMusteriNo = amirKurumMusteriNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYapResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.HavaleYapCevap HavaleYapResult;
        
        public HavaleYapResponse()
        {
        }
        
        public HavaleYapResponse(ZiraatBankPaymentService.HavaleYapCevap HavaleYapResult)
        {
            this.HavaleYapResult = HavaleYapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EftYap", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EftYapRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AliciBanka;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AliciSubeNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string AliciHesapNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string AliciIban;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string AliciAdSoyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string EftTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string Tutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string MusteriReferans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string odemeNedeni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string aliciTcknVkn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string amirAdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string amirHesap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string amirKimlik;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string amirAdres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string amirUlkeSehir;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string amirDogumYeri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string amirDogumTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string amirKurumMusteriNo;
        
        public EftYapRequest()
        {
        }
        
        public EftYapRequest(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string AliciBanka, 
                    string AliciSubeNo, 
                    string AliciHesapNo, 
                    string AliciIban, 
                    string AliciAdSoyad, 
                    string EftTarihi, 
                    string Tutar, 
                    string MusteriReferans, 
                    string Aciklama, 
                    string odemeNedeni, 
                    string aliciTcknVkn, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.AliciBanka = AliciBanka;
            this.AliciSubeNo = AliciSubeNo;
            this.AliciHesapNo = AliciHesapNo;
            this.AliciIban = AliciIban;
            this.AliciAdSoyad = AliciAdSoyad;
            this.EftTarihi = EftTarihi;
            this.Tutar = Tutar;
            this.MusteriReferans = MusteriReferans;
            this.Aciklama = Aciklama;
            this.odemeNedeni = odemeNedeni;
            this.aliciTcknVkn = aliciTcknVkn;
            this.amirAdi = amirAdi;
            this.amirHesap = amirHesap;
            this.amirKimlik = amirKimlik;
            this.amirAdres = amirAdres;
            this.amirUlkeSehir = amirUlkeSehir;
            this.amirDogumYeri = amirDogumYeri;
            this.amirDogumTarihi = amirDogumTarihi;
            this.amirKurumMusteriNo = amirKurumMusteriNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EftYapResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EftYapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.EftYapCevap EftYapResult;
        
        public EftYapResponse()
        {
        }
        
        public EftYapResponse(ZiraatBankPaymentService.EftYapCevap EftYapResult)
        {
            this.EftYapResult = EftYapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DurumSorgula", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DurumSorgulaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MusteriReferans;
        
        public DurumSorgulaRequest()
        {
        }
        
        public DurumSorgulaRequest(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string GonderenMusteriNo, string GonderenEkno, string MusteriReferans)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.MusteriReferans = MusteriReferans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DurumSorgulaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DurumSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.DurumSorgulaCevap DurumSorgulaResult;
        
        public DurumSorgulaResponse()
        {
        }
        
        public DurumSorgulaResponse(ZiraatBankPaymentService.DurumSorgulaCevap DurumSorgulaResult)
        {
            this.DurumSorgulaResult = DurumSorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DurumSorgulaDetay", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DurumSorgulaDetayRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MusteriReferans;
        
        public DurumSorgulaDetayRequest()
        {
        }
        
        public DurumSorgulaDetayRequest(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string GonderenMusteriNo, string GonderenEkno, string MusteriReferans)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.MusteriReferans = MusteriReferans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DurumSorgulaDetayResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DurumSorgulaDetayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.KurumSorgulaDetayCevap DurumSorgulaDetayResult;
        
        public DurumSorgulaDetayResponse()
        {
        }
        
        public DurumSorgulaDetayResponse(ZiraatBankPaymentService.KurumSorgulaDetayCevap DurumSorgulaDetayResult)
        {
            this.DurumSorgulaDetayResult = DurumSorgulaDetayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYapIsimKontrolIle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapIsimKontrolIleRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string aliciSubeKod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AliciMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string AliciEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string iban;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string DovizCinsi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Tutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string MusteriReferans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string TCKNVKN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string adSoyad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string odemeNedeni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string amirAdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string amirHesap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string amirKimlik;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string amirAdres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string amirUlkeSehir;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string amirDogumYeri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string amirDogumTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string amirKurumMusteriNo;
        
        public HavaleYapIsimKontrolIleRequest()
        {
        }
        
        public HavaleYapIsimKontrolIleRequest(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string aliciSubeKod, 
                    string AliciMusteriNo, 
                    string AliciEkno, 
                    string iban, 
                    string DovizCinsi, 
                    string Tutar, 
                    string Aciklama, 
                    string MusteriReferans, 
                    string TCKNVKN, 
                    string adSoyad, 
                    string odemeNedeni, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.aliciSubeKod = aliciSubeKod;
            this.AliciMusteriNo = AliciMusteriNo;
            this.AliciEkno = AliciEkno;
            this.iban = iban;
            this.DovizCinsi = DovizCinsi;
            this.Tutar = Tutar;
            this.Aciklama = Aciklama;
            this.MusteriReferans = MusteriReferans;
            this.TCKNVKN = TCKNVKN;
            this.adSoyad = adSoyad;
            this.odemeNedeni = odemeNedeni;
            this.amirAdi = amirAdi;
            this.amirHesap = amirHesap;
            this.amirKimlik = amirKimlik;
            this.amirAdres = amirAdres;
            this.amirUlkeSehir = amirUlkeSehir;
            this.amirDogumYeri = amirDogumYeri;
            this.amirDogumTarihi = amirDogumTarihi;
            this.amirKurumMusteriNo = amirKurumMusteriNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYapIsimKontrolIleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapIsimKontrolIleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.HavaleYapCevap HavaleYapIsimKontrolIleResult;
        
        public HavaleYapIsimKontrolIleResponse()
        {
        }
        
        public HavaleYapIsimKontrolIleResponse(ZiraatBankPaymentService.HavaleYapCevap HavaleYapIsimKontrolIleResult)
        {
            this.HavaleYapIsimKontrolIleResult = HavaleYapIsimKontrolIleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYapDovizCevrimli", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapDovizCevrimliRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GonderenMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int GonderenEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int AliciTransferSubeKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int AliciTransferMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int AliciTransferEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string AliciTransferIban;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string AliciTransferMusteriAdiSoyadi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string TransferDovizKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int AliciHedefSubeKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int AliciHedefMusteriNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public int AliciHedefEkno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string AliciHedefIban;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string HedefDovizKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public decimal HedefTutar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string Aciklama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string TCKNVKN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string MusteriReferans;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string odemeNedeni;
        
        public HavaleYapDovizCevrimliRequest()
        {
        }
        
        public HavaleYapDovizCevrimliRequest(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    int GonderenMusteriNo, 
                    int GonderenEkno, 
                    int AliciTransferSubeKodu, 
                    int AliciTransferMusteriNo, 
                    int AliciTransferEkno, 
                    string AliciTransferIban, 
                    string AliciTransferMusteriAdiSoyadi, 
                    string TransferDovizKodu, 
                    int AliciHedefSubeKodu, 
                    int AliciHedefMusteriNo, 
                    int AliciHedefEkno, 
                    string AliciHedefIban, 
                    string HedefDovizKodu, 
                    decimal HedefTutar, 
                    string Aciklama, 
                    string TCKNVKN, 
                    string MusteriReferans, 
                    string odemeNedeni)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.GonderenMusteriNo = GonderenMusteriNo;
            this.GonderenEkno = GonderenEkno;
            this.AliciTransferSubeKodu = AliciTransferSubeKodu;
            this.AliciTransferMusteriNo = AliciTransferMusteriNo;
            this.AliciTransferEkno = AliciTransferEkno;
            this.AliciTransferIban = AliciTransferIban;
            this.AliciTransferMusteriAdiSoyadi = AliciTransferMusteriAdiSoyadi;
            this.TransferDovizKodu = TransferDovizKodu;
            this.AliciHedefSubeKodu = AliciHedefSubeKodu;
            this.AliciHedefMusteriNo = AliciHedefMusteriNo;
            this.AliciHedefEkno = AliciHedefEkno;
            this.AliciHedefIban = AliciHedefIban;
            this.HedefDovizKodu = HedefDovizKodu;
            this.HedefTutar = HedefTutar;
            this.Aciklama = Aciklama;
            this.TCKNVKN = TCKNVKN;
            this.MusteriReferans = MusteriReferans;
            this.odemeNedeni = odemeNedeni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HavaleYapDovizCevrimliResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HavaleYapDovizCevrimliResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.HavaleYapCevap HavaleYapDovizCevrimliResult;
        
        public HavaleYapDovizCevrimliResponse()
        {
        }
        
        public HavaleYapDovizCevrimliResponse(ZiraatBankPaymentService.HavaleYapCevap HavaleYapDovizCevrimliResult)
        {
            this.HavaleYapDovizCevrimliResult = HavaleYapDovizCevrimliResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IbanSorgula", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IbanSorgulaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string iban;
        
        public IbanSorgulaRequest()
        {
        }
        
        public IbanSorgulaRequest(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string iban)
        {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.iban = iban;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IbanSorgulaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IbanSorgulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ZiraatBankPaymentService.IbanSorgulamaCevap IbanSorgulaResult;
        
        public IbanSorgulaResponse()
        {
        }
        
        public IbanSorgulaResponse(ZiraatBankPaymentService.IbanSorgulamaCevap IbanSorgulaResult)
        {
            this.IbanSorgulaResult = IbanSorgulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface NkyParaTransferiWSSoapChannel : ZiraatBankPaymentService.NkyParaTransferiWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NkyParaTransferiWSSoapClient : System.ServiceModel.ClientBase<ZiraatBankPaymentService.NkyParaTransferiWSSoap>, ZiraatBankPaymentService.NkyParaTransferiWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NkyParaTransferiWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NkyParaTransferiWSSoapClient.GetBindingForEndpoint(endpointConfiguration), NkyParaTransferiWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkyParaTransferiWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NkyParaTransferiWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkyParaTransferiWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NkyParaTransferiWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NkyParaTransferiWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.HavaleYapAsync(ZiraatBankPaymentService.HavaleYapRequest request)
        {
            return base.Channel.HavaleYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapResponse> HavaleYapAsync(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string AliciMusteriNo, 
                    string AliciEkno, 
                    string iban, 
                    string DovizCinsi, 
                    string Tutar, 
                    string Aciklama, 
                    string MusteriReferans, 
                    string TCKNVKN, 
                    string odemeNedeni, 
                    string aliciHesapKapaliysaAcikHesabiBul, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            ZiraatBankPaymentService.HavaleYapRequest inValue = new ZiraatBankPaymentService.HavaleYapRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.AliciMusteriNo = AliciMusteriNo;
            inValue.AliciEkno = AliciEkno;
            inValue.iban = iban;
            inValue.DovizCinsi = DovizCinsi;
            inValue.Tutar = Tutar;
            inValue.Aciklama = Aciklama;
            inValue.MusteriReferans = MusteriReferans;
            inValue.TCKNVKN = TCKNVKN;
            inValue.odemeNedeni = odemeNedeni;
            inValue.aliciHesapKapaliysaAcikHesabiBul = aliciHesapKapaliysaAcikHesabiBul;
            inValue.amirAdi = amirAdi;
            inValue.amirHesap = amirHesap;
            inValue.amirKimlik = amirKimlik;
            inValue.amirAdres = amirAdres;
            inValue.amirUlkeSehir = amirUlkeSehir;
            inValue.amirDogumYeri = amirDogumYeri;
            inValue.amirDogumTarihi = amirDogumTarihi;
            inValue.amirKurumMusteriNo = amirKurumMusteriNo;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).HavaleYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.EftYapResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.EftYapAsync(ZiraatBankPaymentService.EftYapRequest request)
        {
            return base.Channel.EftYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.EftYapResponse> EftYapAsync(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string AliciBanka, 
                    string AliciSubeNo, 
                    string AliciHesapNo, 
                    string AliciIban, 
                    string AliciAdSoyad, 
                    string EftTarihi, 
                    string Tutar, 
                    string MusteriReferans, 
                    string Aciklama, 
                    string odemeNedeni, 
                    string aliciTcknVkn, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            ZiraatBankPaymentService.EftYapRequest inValue = new ZiraatBankPaymentService.EftYapRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.AliciBanka = AliciBanka;
            inValue.AliciSubeNo = AliciSubeNo;
            inValue.AliciHesapNo = AliciHesapNo;
            inValue.AliciIban = AliciIban;
            inValue.AliciAdSoyad = AliciAdSoyad;
            inValue.EftTarihi = EftTarihi;
            inValue.Tutar = Tutar;
            inValue.MusteriReferans = MusteriReferans;
            inValue.Aciklama = Aciklama;
            inValue.odemeNedeni = odemeNedeni;
            inValue.aliciTcknVkn = aliciTcknVkn;
            inValue.amirAdi = amirAdi;
            inValue.amirHesap = amirHesap;
            inValue.amirKimlik = amirKimlik;
            inValue.amirAdres = amirAdres;
            inValue.amirUlkeSehir = amirUlkeSehir;
            inValue.amirDogumYeri = amirDogumYeri;
            inValue.amirDogumTarihi = amirDogumTarihi;
            inValue.amirKurumMusteriNo = amirKurumMusteriNo;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).EftYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.DurumSorgulaAsync(ZiraatBankPaymentService.DurumSorgulaRequest request)
        {
            return base.Channel.DurumSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaResponse> DurumSorgulaAsync(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string GonderenMusteriNo, string GonderenEkno, string MusteriReferans)
        {
            ZiraatBankPaymentService.DurumSorgulaRequest inValue = new ZiraatBankPaymentService.DurumSorgulaRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.MusteriReferans = MusteriReferans;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).DurumSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaDetayResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.DurumSorgulaDetayAsync(ZiraatBankPaymentService.DurumSorgulaDetayRequest request)
        {
            return base.Channel.DurumSorgulaDetayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.DurumSorgulaDetayResponse> DurumSorgulaDetayAsync(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string GonderenMusteriNo, string GonderenEkno, string MusteriReferans)
        {
            ZiraatBankPaymentService.DurumSorgulaDetayRequest inValue = new ZiraatBankPaymentService.DurumSorgulaDetayRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.MusteriReferans = MusteriReferans;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).DurumSorgulaDetayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapIsimKontrolIleResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.HavaleYapIsimKontrolIleAsync(ZiraatBankPaymentService.HavaleYapIsimKontrolIleRequest request)
        {
            return base.Channel.HavaleYapIsimKontrolIleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapIsimKontrolIleResponse> HavaleYapIsimKontrolIleAsync(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    string GonderenMusteriNo, 
                    string GonderenEkno, 
                    string aliciSubeKod, 
                    string AliciMusteriNo, 
                    string AliciEkno, 
                    string iban, 
                    string DovizCinsi, 
                    string Tutar, 
                    string Aciklama, 
                    string MusteriReferans, 
                    string TCKNVKN, 
                    string adSoyad, 
                    string odemeNedeni, 
                    string amirAdi, 
                    string amirHesap, 
                    string amirKimlik, 
                    string amirAdres, 
                    string amirUlkeSehir, 
                    string amirDogumYeri, 
                    string amirDogumTarihi, 
                    string amirKurumMusteriNo)
        {
            ZiraatBankPaymentService.HavaleYapIsimKontrolIleRequest inValue = new ZiraatBankPaymentService.HavaleYapIsimKontrolIleRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.aliciSubeKod = aliciSubeKod;
            inValue.AliciMusteriNo = AliciMusteriNo;
            inValue.AliciEkno = AliciEkno;
            inValue.iban = iban;
            inValue.DovizCinsi = DovizCinsi;
            inValue.Tutar = Tutar;
            inValue.Aciklama = Aciklama;
            inValue.MusteriReferans = MusteriReferans;
            inValue.TCKNVKN = TCKNVKN;
            inValue.adSoyad = adSoyad;
            inValue.odemeNedeni = odemeNedeni;
            inValue.amirAdi = amirAdi;
            inValue.amirHesap = amirHesap;
            inValue.amirKimlik = amirKimlik;
            inValue.amirAdres = amirAdres;
            inValue.amirUlkeSehir = amirUlkeSehir;
            inValue.amirDogumYeri = amirDogumYeri;
            inValue.amirDogumTarihi = amirDogumTarihi;
            inValue.amirKurumMusteriNo = amirKurumMusteriNo;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).HavaleYapIsimKontrolIleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapDovizCevrimliResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.HavaleYapDovizCevrimliAsync(ZiraatBankPaymentService.HavaleYapDovizCevrimliRequest request)
        {
            return base.Channel.HavaleYapDovizCevrimliAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.HavaleYapDovizCevrimliResponse> HavaleYapDovizCevrimliAsync(
                    ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, 
                    int GonderenMusteriNo, 
                    int GonderenEkno, 
                    int AliciTransferSubeKodu, 
                    int AliciTransferMusteriNo, 
                    int AliciTransferEkno, 
                    string AliciTransferIban, 
                    string AliciTransferMusteriAdiSoyadi, 
                    string TransferDovizKodu, 
                    int AliciHedefSubeKodu, 
                    int AliciHedefMusteriNo, 
                    int AliciHedefEkno, 
                    string AliciHedefIban, 
                    string HedefDovizKodu, 
                    decimal HedefTutar, 
                    string Aciklama, 
                    string TCKNVKN, 
                    string MusteriReferans, 
                    string odemeNedeni)
        {
            ZiraatBankPaymentService.HavaleYapDovizCevrimliRequest inValue = new ZiraatBankPaymentService.HavaleYapDovizCevrimliRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.GonderenMusteriNo = GonderenMusteriNo;
            inValue.GonderenEkno = GonderenEkno;
            inValue.AliciTransferSubeKodu = AliciTransferSubeKodu;
            inValue.AliciTransferMusteriNo = AliciTransferMusteriNo;
            inValue.AliciTransferEkno = AliciTransferEkno;
            inValue.AliciTransferIban = AliciTransferIban;
            inValue.AliciTransferMusteriAdiSoyadi = AliciTransferMusteriAdiSoyadi;
            inValue.TransferDovizKodu = TransferDovizKodu;
            inValue.AliciHedefSubeKodu = AliciHedefSubeKodu;
            inValue.AliciHedefMusteriNo = AliciHedefMusteriNo;
            inValue.AliciHedefEkno = AliciHedefEkno;
            inValue.AliciHedefIban = AliciHedefIban;
            inValue.HedefDovizKodu = HedefDovizKodu;
            inValue.HedefTutar = HedefTutar;
            inValue.Aciklama = Aciklama;
            inValue.TCKNVKN = TCKNVKN;
            inValue.MusteriReferans = MusteriReferans;
            inValue.odemeNedeni = odemeNedeni;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).HavaleYapDovizCevrimliAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.KurCevap> OkuKurAsync(string dovizKodu)
        {
            return base.Channel.OkuKurAsync(dovizKodu);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZiraatBankPaymentService.IbanSorgulaResponse> ZiraatBankPaymentService.NkyParaTransferiWSSoap.IbanSorgulaAsync(ZiraatBankPaymentService.IbanSorgulaRequest request)
        {
            return base.Channel.IbanSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZiraatBankPaymentService.IbanSorgulaResponse> IbanSorgulaAsync(ZiraatBankPaymentService.SecuredWebServiceHeader SecuredWebServiceHeader, string iban)
        {
            ZiraatBankPaymentService.IbanSorgulaRequest inValue = new ZiraatBankPaymentService.IbanSorgulaRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.iban = iban;
            return ((ZiraatBankPaymentService.NkyParaTransferiWSSoap)(this)).IbanSorgulaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NkyParaTransferiWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NkyParaTransferiWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NkyParaTransferiWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://odm.ziraatbank.com.tr:12178/NKYParaTransferiWS/NKYParaTransferiWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NkyParaTransferiWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://odm.ziraatbank.com.tr:12178/NKYParaTransferiWS/NKYParaTransferiWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NkyParaTransferiWSSoap,
            
            NkyParaTransferiWSSoap12,
        }
    }
}
