//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalkbankWSDL
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HesapEkstreRequest", Namespace="http://schemas.datacontract.org/2004/07/HesapEkstreOrtakWS.Request")]
    public partial class HesapEkstreRequest : object
    {
        
        private System.DateTime BaslangicTarihiField;
        
        private System.DateTime BitisTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaslangicTarihi   
        {
            get
            {
                return this.BaslangicTarihiField;
            }
            set
            {
                this.BaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BitisTarihi
        {
            get
            {
                return this.BitisTarihiField;
            }
            set
            {
                this.BitisTarihiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HesapEkstreResponse", Namespace="http://schemas.datacontract.org/2004/07/HesapEkstreOrtakWS.Response")]
    public partial class HesapEkstreResponse : object
    {
        
        private string HataAciklamaField;
        
        private string HataKoduField;
        
        private HalkbankWSDL.Hesap[] HesaplarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataAciklama
        {
            get
            {
                return this.HataAciklamaField;
            }
            set
            {
                this.HataAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HalkbankWSDL.Hesap[] Hesaplar
        {
            get
            {
                return this.HesaplarField;
            }
            set
            {
                this.HesaplarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hesap", Namespace="https://webservice.halkbank.com.tr")]
    public partial class Hesap : object
    {
        
        private string BakiyeField;
        
        private string BlokeMeblagField;
        
        private string FaizOraniField;
        
        private HalkbankWSDL.Hareket[] HareketlerField;
        
        private string HesapAcilisTarihiField;
        
        private string HesapAdiField;
        
        private string HesapCinsiField;
        
        private string HesapNoField;
        
        private string HesapTuruField;
        
        private string IbanNoField;
        
        private string KrediLimitField;
        
        private string KrediliKullanilabilirBakiyeField;
        
        private string KullanilabilirBakiyeField;
        
        private string MusteriNoField;
        
        private string SonHareketTarihiField;
        
        private string SubeAdiField;
        
        private string SubeKoduField;
        
        private string VadeTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bakiye
        {
            get
            {
                return this.BakiyeField;
            }
            set
            {
                this.BakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlokeMeblag
        {
            get
            {
                return this.BlokeMeblagField;
            }
            set
            {
                this.BlokeMeblagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaizOrani
        {
            get
            {
                return this.FaizOraniField;
            }
            set
            {
                this.FaizOraniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HalkbankWSDL.Hareket[] Hareketler
        {
            get
            {
                return this.HareketlerField;
            }
            set
            {
                this.HareketlerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapAcilisTarihi
        {
            get
            {
                return this.HesapAcilisTarihiField;
            }
            set
            {
                this.HesapAcilisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapAdi
        {
            get
            {
                return this.HesapAdiField;
            }
            set
            {
                this.HesapAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapCinsi
        {
            get
            {
                return this.HesapCinsiField;
            }
            set
            {
                this.HesapCinsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapTuru
        {
            get
            {
                return this.HesapTuruField;
            }
            set
            {
                this.HesapTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IbanNo
        {
            get
            {
                return this.IbanNoField;
            }
            set
            {
                this.IbanNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KrediLimit
        {
            get
            {
                return this.KrediLimitField;
            }
            set
            {
                this.KrediLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KrediliKullanilabilirBakiye
        {
            get
            {
                return this.KrediliKullanilabilirBakiyeField;
            }
            set
            {
                this.KrediliKullanilabilirBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullanilabilirBakiye
        {
            get
            {
                return this.KullanilabilirBakiyeField;
            }
            set
            {
                this.KullanilabilirBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SonHareketTarihi
        {
            get
            {
                return this.SonHareketTarihiField;
            }
            set
            {
                this.SonHareketTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeAdi
        {
            get
            {
                return this.SubeAdiField;
            }
            set
            {
                this.SubeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeKodu
        {
            get
            {
                return this.SubeKoduField;
            }
            set
            {
                this.SubeKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VadeTarihi
        {
            get
            {
                return this.VadeTarihiField;
            }
            set
            {
                this.VadeTarihiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hareket", Namespace="https://webservice.halkbank.com.tr")]
    public partial class Hareket : object
    {
        
        private string AciklamaField;
        
        private string AtmNoField;
        
        private string BakiyeField;
        
        private string DekontNoField;
        
        private string EkBilgiField;
        
        private string EkstreAciklamaField;
        
        private string HareketTutariField;
        
        private string IptalField;
        
        private string IslemKodField;
        
        private string IslemYapanAdSoyadField;
        
        private string IslemYapanKimlikNoField;
        
        private string KarsiAdSoyadField;
        
        private int KarsiBankaKodField;
        
        private string KarsiHesapIBANField;
        
        private string KarsiKimlikNoField;
        
        private string KarsiMusteriNoField;
        
        private int KarsiSubeKodField;
        
        private string ReferansNoField;
        
        private string SaatField;
        
        private string SiranoField;
        
        private string TarihField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtmNo
        {
            get
            {
                return this.AtmNoField;
            }
            set
            {
                this.AtmNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bakiye
        {
            get
            {
                return this.BakiyeField;
            }
            set
            {
                this.BakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DekontNo
        {
            get
            {
                return this.DekontNoField;
            }
            set
            {
                this.DekontNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkBilgi
        {
            get
            {
                return this.EkBilgiField;
            }
            set
            {
                this.EkBilgiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EkstreAciklama
        {
            get
            {
                return this.EkstreAciklamaField;
            }
            set
            {
                this.EkstreAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HareketTutari
        {
            get
            {
                return this.HareketTutariField;
            }
            set
            {
                this.HareketTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iptal
        {
            get
            {
                return this.IptalField;
            }
            set
            {
                this.IptalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemKod
        {
            get
            {
                return this.IslemKodField;
            }
            set
            {
                this.IslemKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemYapanAdSoyad
        {
            get
            {
                return this.IslemYapanAdSoyadField;
            }
            set
            {
                this.IslemYapanAdSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemYapanKimlikNo
        {
            get
            {
                return this.IslemYapanKimlikNoField;
            }
            set
            {
                this.IslemYapanKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KarsiAdSoyad
        {
            get
            {
                return this.KarsiAdSoyadField;
            }
            set
            {
                this.KarsiAdSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KarsiBankaKod
        {
            get
            {
                return this.KarsiBankaKodField;
            }
            set
            {
                this.KarsiBankaKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KarsiHesapIBAN
        {
            get
            {
                return this.KarsiHesapIBANField;
            }
            set
            {
                this.KarsiHesapIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KarsiKimlikNo
        {
            get
            {
                return this.KarsiKimlikNoField;
            }
            set
            {
                this.KarsiKimlikNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KarsiMusteriNo
        {
            get
            {
                return this.KarsiMusteriNoField;
            }
            set
            {
                this.KarsiMusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KarsiSubeKod
        {
            get
            {
                return this.KarsiSubeKodField;
            }
            set
            {
                this.KarsiSubeKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferansNo
        {
            get
            {
                return this.ReferansNoField;
            }
            set
            {
                this.ReferansNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Saat
        {
            get
            {
                return this.SaatField;
            }
            set
            {
                this.SaatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sirano
        {
            get
            {
                return this.SiranoField;
            }
            set
            {
                this.SiranoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tarih
        {
            get
            {
                return this.TarihField;
            }
            set
            {
                this.TarihField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BagliHesapEkstreRequest", Namespace="http://schemas.datacontract.org/2004/07/HesapEkstreOrtakWS.Request")]
    public partial class BagliHesapEkstreRequest : object
    {
        
        private string BagliMusteriNumarasiField;
        
        private System.DateTime BaslangicTarihiField;
        
        private System.DateTime BitisTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BagliMusteriNumarasi
        {
            get
            {
                return this.BagliMusteriNumarasiField;
            }
            set
            {
                this.BagliMusteriNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaslangicTarihi
        {
            get
            {
                return this.BaslangicTarihiField;
            }
            set
            {
                this.BaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BitisTarihi
        {
            get
            {
                return this.BitisTarihiField;
            }
            set
            {
                this.BitisTarihiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DekontRequest", Namespace="http://schemas.datacontract.org/2004/07/HesapEkstreOrtakWS.Request")]
    public partial class DekontRequest : object
    {
        
        private string DekontNoField;
        
        private string HesapNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DekontNo
        {
            get
            {
                return this.DekontNoField;
            }
            set
            {
                this.DekontNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DekontResponse", Namespace="https://webservice.halkbank.com.tr")]
    public partial class DekontResponse : object
    {
        
        private HalkbankWSDL.Dekont[] DekontlarField;
        
        private string HataAciklamaField;
        
        private string HataKoduField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HalkbankWSDL.Dekont[] Dekontlar
        {
            get
            {
                return this.DekontlarField;
            }
            set
            {
                this.DekontlarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataAciklama
        {
            get
            {
                return this.HataAciklamaField;
            }
            set
            {
                this.HataAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dekont", Namespace="https://webservice.halkbank.com.tr")]
    public partial class Dekont : object
    {
        
        private string DekontDosyaTuruField;
        
        private byte[] DekontIcerikField;
        
        private string DekontNoField;
        
        private string HesapNoField;
        
        private string IptalFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DekontDosyaTuru
        {
            get
            {
                return this.DekontDosyaTuruField;
            }
            set
            {
                this.DekontDosyaTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DekontIcerik
        {
            get
            {
                return this.DekontIcerikField;
            }
            set
            {
                this.DekontIcerikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DekontNo
        {
            get
            {
                return this.DekontNoField;
            }
            set
            {
                this.DekontNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IptalFlag
        {
            get
            {
                return this.IptalFlagField;
            }
            set
            {
                this.IptalFlagField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHesapEkstreOrtak")]
    public interface IHesapEkstreOrtak
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtak/EkstreSorgulama", ReplyAction="http://tempuri.org/IHesapEkstreOrtak/EkstreSorgulamaResponse")]
        System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> EkstreSorgulamaAsync(HalkbankWSDL.HesapEkstreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtak/BagliMusteriEkstreSorgulama", ReplyAction="http://tempuri.org/IHesapEkstreOrtak/BagliMusteriEkstreSorgulamaResponse")]
        System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> BagliMusteriEkstreSorgulamaAsync(HalkbankWSDL.BagliHesapEkstreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtak/DekontSorgulama", ReplyAction="http://tempuri.org/IHesapEkstreOrtak/DekontSorgulamaResponse")]
        System.Threading.Tasks.Task<HalkbankWSDL.DekontResponse> DekontSorgulamaAsync(HalkbankWSDL.DekontRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IHesapEkstreOrtakChannel : HalkbankWSDL.IHesapEkstreOrtak, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HesapEkstreOrtakClient : System.ServiceModel.ClientBase<HalkbankWSDL.IHesapEkstreOrtak>, HalkbankWSDL.IHesapEkstreOrtak
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HesapEkstreOrtakClient() : 
                base(HesapEkstreOrtakClient.GetDefaultBinding(), HesapEkstreOrtakClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basicHttpEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakClient(EndpointConfiguration endpointConfiguration) : 
                base(HesapEkstreOrtakClient.GetBindingForEndpoint(endpointConfiguration), HesapEkstreOrtakClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HesapEkstreOrtakClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HesapEkstreOrtakClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> EkstreSorgulamaAsync(HalkbankWSDL.HesapEkstreRequest request)
        {
            return base.Channel.EkstreSorgulamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> BagliMusteriEkstreSorgulamaAsync(HalkbankWSDL.BagliHesapEkstreRequest request)
        {
            return base.Channel.BagliMusteriEkstreSorgulamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.DekontResponse> DekontSorgulamaAsync(HalkbankWSDL.DekontRequest request)
        {
            return base.Channel.DekontSorgulamaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.halkbank.com.tr/HesapEkstreOrtakWS/HesapEkstreOrtak.svc/Basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HesapEkstreOrtakClient.GetBindingForEndpoint(EndpointConfiguration.basicHttpEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HesapEkstreOrtakClient.GetEndpointAddress(EndpointConfiguration.basicHttpEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            basicHttpEndpoint,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHesapEkstreOrtakBasic")]
    public interface IHesapEkstreOrtakBasic
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtakBasic/EkstreSorgulamaBasic", ReplyAction="http://tempuri.org/IHesapEkstreOrtakBasic/EkstreSorgulamaBasicResponse")]
        System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> EkstreSorgulamaBasicAsync(HalkbankWSDL.HesapEkstreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtakBasic/BagliMusteriEkstreSorgulamaBasic", ReplyAction="http://tempuri.org/IHesapEkstreOrtakBasic/BagliMusteriEkstreSorgulamaBasicRespons" +
            "e")]
        System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> BagliMusteriEkstreSorgulamaBasicAsync(HalkbankWSDL.BagliHesapEkstreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHesapEkstreOrtakBasic/DekontSorgulamaBasic", ReplyAction="http://tempuri.org/IHesapEkstreOrtakBasic/DekontSorgulamaBasicResponse")]
        System.Threading.Tasks.Task<HalkbankWSDL.DekontResponse> DekontSorgulamaBasicAsync(HalkbankWSDL.DekontRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IHesapEkstreOrtakBasicChannel : HalkbankWSDL.IHesapEkstreOrtakBasic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HesapEkstreOrtakBasicClient : System.ServiceModel.ClientBase<HalkbankWSDL.IHesapEkstreOrtakBasic>, HalkbankWSDL.IHesapEkstreOrtakBasic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HesapEkstreOrtakBasicClient() : 
                base(HesapEkstreOrtakBasicClient.GetDefaultBinding(), HesapEkstreOrtakBasicClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basicHttpEndpoint1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakBasicClient(EndpointConfiguration endpointConfiguration) : 
                base(HesapEkstreOrtakBasicClient.GetBindingForEndpoint(endpointConfiguration), HesapEkstreOrtakBasicClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakBasicClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HesapEkstreOrtakBasicClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakBasicClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HesapEkstreOrtakBasicClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HesapEkstreOrtakBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> EkstreSorgulamaBasicAsync(HalkbankWSDL.HesapEkstreRequest request)
        {
            return base.Channel.EkstreSorgulamaBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.HesapEkstreResponse> BagliMusteriEkstreSorgulamaBasicAsync(HalkbankWSDL.BagliHesapEkstreRequest request)
        {
            return base.Channel.BagliMusteriEkstreSorgulamaBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<HalkbankWSDL.DekontResponse> DekontSorgulamaBasicAsync(HalkbankWSDL.DekontRequest request)
        {
            return base.Channel.DekontSorgulamaBasicAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicHttpEndpoint1))
            {
                return new System.ServiceModel.EndpointAddress("https://webservice.halkbank.com.tr/HesapEkstreOrtakWS/HesapEkstreOrtak.svc/SoapBa" +
                        "sic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HesapEkstreOrtakBasicClient.GetBindingForEndpoint(EndpointConfiguration.basicHttpEndpoint1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HesapEkstreOrtakBasicClient.GetEndpointAddress(EndpointConfiguration.basicHttpEndpoint1);
        }
        
        public enum EndpointConfiguration
        {
            
            basicHttpEndpoint1,
        }
    }
}
